### ISSUE TITLE
Font female 

### ISSUE THREAD

**Issue by ghost** [kaurovandrii96/f5project-kaurov#5]
https://github.com/kaurovandrii96/f5project-kaurov/blob/af0977b07b20a97c83dab7a94cf74faa6085e878/src/sass/_typography.scss#L32

Почему  ты подлючил лишни начертания шрифта?? Шрифт подключен не правильно

**Comment by kaurovandrii96** [comment]
Лишние шрифты удалил, вроде все правильно подключено
